---
- name: Configurar prerequisitos
  hosts: elasticsearch
  become: true
  roles:
    - elk-prerequisitos
  tags: elk-prerequisitos

- name: Install Elasticsearch
  hosts: elasticsearch 
  become: true
  roles:
    - elasticsearch
  vars:
    file_location: "{{ rpm_location }}"
  tags: elasticsearch

- name: Install Kibana
  hosts: kibana
  become: true
  roles:
    - kibana
  tags: kibana

- name: Install Elastic Beats
  hosts: beat
  become: true
  tasks:
    - name: Install beats
      include_role:
        name: beat
      vars:
        - beat_name: "{{ item }}"
      loop:
        - metricbeat
        - filebeat
        - auditbeat
        - packetbeat
  tags: beat
