---
- name: Copy the rpm to the server
  copy:
    src: "{{ pkg_location | default('files') }}/kibana.rpm"
    dest: /root/

- name: Install the kibana package
  yum:
    name: /root/kibana.rpm
    state: present
...
