---
- name: Copy the rpm to the server
  copy:
    src: "{{ file_location | default('files') }}/elasticsearch.rpm"
    dest: /root/

- name: Install the elasticsearch package
  yum:
    name: /root/elasticsearch.rpm
    state: present
