---
- name: Copy the .deb to the server
  copy:
    src: "{{ pkg_location | default('files') }}/{{ beat_name }}.deb"
    dest: /root/

- name: Install the {{ beat_name }} package
  apt:
    deb: /root/{{ beat_name }}.deb
